### ISSUE TITLE
使用自己的数据集

### ISSUE THREAD

**Issue by Angzz** [MTCloudVision/mxnet-dssd#2]
您好，请问您能给下用自己的数据集训练的命令吗，我的图像是2048X2048的，不知道resize到什么样比较合适。

另外，我想请问下K-MEANS选取合适的scales和ratios是怎么实现的呢

**Comment by MTCloudVision** [comment]
1.不太明白用自己的数据集训练的命令具体指的是什么。resize的大小感觉应该根据你数据集里的物体大小去调整。
2.这里我们没有实现论文里提到的聚类的方法，里面应该是和其它聚类的方法差不多，计算default box 和gt 的 iou loss。可以参考下这里的代码。https://github.com/leetenki/YOLOv2/blob/cd2b69c36ccee8babc0ba013ab47bc8f4177c850/dimension_cluster.py

**Comment by xubo00** [comment]
xubo@ubuntu:~/run/mxnet-dssd-master$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 153, in <module>
    ctx, len(class_names), args.nms_thresh, args.force_nms)
  File "demo.py", line 56, in get_detector
    force_nms=force_nms, nms_topk=nms_topk)
  File "/home/xubo/run/mxnet-dssd-master/symbol/symbol_factory.py", line 236, in get_symbol
    return symbol_builder.get_symbol(**config)
TypeError: get_symbol() takes at least 10 arguments (12 given)
@Angzz @MTCloudVision 
请问你们遇到过这个问题吗?

**Comment by Angzz** [comment]
@xubo0321 你这个问题就是参数位置错了啊。。。。

**Comment by xubo00** [comment]
怎么讲??我什么也没有改变啊. @Angzz
