### ISSUE TITLE
反卷积模块和其后预测模块输出通道数为什么是num_filters[::-1][k-1]，而TDM模块的输出通道数为num_filters[::-1][k]，不应该都是num_filters[::-1][k]吗？

### ISSUE THREAD

**Issue by luckyboylch** [MTCloudVision/mxnet-dssd#3]
def construct_dssd_deconv_layer
       ..........
        concat_conv = deconvolution_module(from_layer,conv,num_filters[::-1][k-1],2,k)
        anti_layers[k] = concat_conv
        if use_perdict_module[::-1][k]>1:
            dssd_from_layers.append(prediction_module(concat_conv,num_filters[::-1][k-1]))
        else :
            dssd_from_layers.append(concat_conv)
    return dssd_from_layers[::-1]

def construct_topdown_upsample_layer(from_layers, num_filters):
       ........
        concat_conv = topdown_upsample(from_layer,conv,num_filters[::-1][k],2,k)
        anti_layers[k] = concat_conv
        tdm_from_layers.append(concat_conv)
    return tdm_from_layers[::-1]

**Comment by MTCloudVision** [comment]
减1这个操作是仿照论文里的样子，使得输出维度和高层特征维度相同，而tdm结构的并没有找到源码。我们按照我们认为合理的方式实现的，即对较小的高层特征图没有采用tdm结构。使用tdm结构的层输出特征维度仿照论文和低层特征维度相同。所以有了这样的差别。

**Comment by xubo00** [comment]
xubo@ubuntu:~/run/mxnet-dssd-master$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 153, in <module>
    ctx, len(class_names), args.nms_thresh, args.force_nms)
  File "demo.py", line 56, in get_detector
    force_nms=force_nms, nms_topk=nms_topk)
  File "/home/xubo/run/mxnet-dssd-master/symbol/symbol_factory.py", line 236, in get_symbol
    return symbol_builder.get_symbol(**config)
TypeError: get_symbol() takes at least 10 arguments (12 given)
@luckyboylch 
请问您遇到过这个问题吗?
