### ISSUE TITLE
请问pretrained的resnet-321模型有吗

### ISSUE THREAD

**Issue by dingqunfei** [MTCloudVision/mxnet-dssd#4]

**Comment by xubo00** [comment]
xubo@ubuntu:~/run/mxnet-dssd-master$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 153, in <module>
    ctx, len(class_names), args.nms_thresh, args.force_nms)
  File "demo.py", line 56, in get_detector
    force_nms=force_nms, nms_topk=nms_topk)
  File "/home/xubo/run/mxnet-dssd-master/symbol/symbol_factory.py", line 236, in get_symbol
    return symbol_builder.get_symbol(**config)
TypeError: get_symbol() takes at least 10 arguments (12 given)
@dingqunfei 
请问您遇到过这个问题吗?
