### ISSUE TITLE
when i run densenet,

### ISSUE THREAD

**Issue by bitwangdan** [MTCloudVision/mxnet-dssd#9]
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    voc07_metric=args.use_voc07_metric)
  File "/home/danny.wd/gitlab/mxnet-dssd-master/train/train_net.py", line 198, in train_net
    nms_thresh=nms_thresh, force_suppress=force_suppress, nms_topk=nms_topk)
  File "/home/danny.wd/gitlab/mxnet-dssd-master/symbol/symbol_factory.py", line 228, in get_symbol_train
    return symbol_builder.get_symbol_train(**config)
  File "/home/danny.wd/gitlab/mxnet-dssd-master/symbol/symbol_builder.py", line 88, in get_symbol_train
    num_channels=num_filters, clip=False, interm_layer=0, steps=steps, use_tdm=use_tdm)
  File "/home/danny.wd/gitlab/mxnet-dssd-master/symbol/common.py", line 251, in multibox_layer
    from_layers = dt.construct_dssd_deconv_layer(from_layers, num_filters, topdown_layers, use_perdict_module)
  File "/home/danny.wd/gitlab/mxnet-dssd-master/symbol/dssd_tdm.py", line 56, in construct_dssd_deconv_layer
    concat_conv = deconvolution_module(from_layer,conv,num_filters[::-1][k-1],2,k)
  File "/home/danny.wd/gitlab/mxnet-dssd-master/symbol/dssd_tdm.py", line 17, in deconvolution_module
    data=conv2, kernel=(2, 2), stride=(upstrid, upstrid),num_filter=num_filter, attr={'lr_mult': '%f' % lr_mult}, name="{}de_{}".format(conv2.name, str(level)))
  File "<string>", line 110, in Deconvolution
  File "/home/danny.wd/gitlab/mxnet-ssd/mxnet/python/mxnet/_ctypes/symbol.py", line 127, in _symbol_creator
    ctypes.byref(sym_handle)))
  File "/home/danny.wd/gitlab/mxnet-ssd/mxnet/python/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: value 4294967295 for Parameter num_filter exceed bound [1,100000], in operator Deconvolution(name="", num_filter="-1", stride="(2, 2)", kernel="(2, 2)", __lr_mult__="1.000000")

**Comment by bitwangdan** [comment]
does anyone meet this problem?
